UPDATE - update-archie script, add bash-colors file for easy color echoing

diff --git a/bin/update-archie b/bin/update-archie
--- a/bin/update-archie
+++ b/bin/update-archie
@@ -2,33 +2,45 @@
 # vim: set softtabstop=2 ts=2 sw=2 expandtab: 
 # Settings
 ABS_PATH=$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)
+source ${ABS_PATH}/bash-colors
 #CONTENT=$ARGV[0]
 #DATE=`date +%F`
 
-echo "Backing up Existing Configuration"
+echo -e "${Green}Checking for Local Changes${Off}"
+if git diff-index --quiet HEAD --; then
+  echo -e "  ${Green}No Changes found continuing${Off}" 
+else
+  echo -e "  ${BRed}Local changes found exiting without updating${Cyan}"
+  git diff-index HEAD --
+  echo -e "${Off}"
+  exit 1
+fi
+
+
+echo -e "${Green}Backing up Existing Configuration${Off}"
 if [ ! -d ${ABS_PATH}/../config.bak ] 
 then
   mkdir ${ABS_PATH}/../config.bak
 fi
 cp -rf ${ABS_PATH}/../config/* ${ABS_PATH}/../config.bak/
 
-echo "Updating to Latest Archie version"
+echo -e "${Green}Updating to Latest Archie version${Off}"
 cd ${ABS_PATH}/../
 git pull
 
 if [ ! -f ${ABS_PATH}/../config/settings.php ]
 then
- echo "ERROR: No settings file found, it appears as though archie isn't installed."
+ echo -e "${Red}ERROR: No settings file found, it appears as though archie isn't installed.${Off}"
 fi
 
 if [ ! -f ${ABS_PATH}/../config/units.csv ]
 then
  if [ -f ${ABS_PATH}/../config.bak/units.csv ]
  then
-   echo "WARNING: Restoring previous Units file, may differ from stock units file provided by Archie"
+   echo -e "${Yello}WARNING: Restoring previous Units file, may differ from stock units file provided by Archie${Off}"
    cp ${ABS_PATH}/../config.bak/units.csv ${ABS_PATH}/../config/units.csv
  else
-   echo "WARNING: Units config not found, copying dist into place."
+   echo -e "${Yellow}WARNING: Units config not found, copying dist into place.${Off}"
    cp ${ABS_PATH}/../config/units.csv.dist ${ABS_PATH}/../config/units.csv
  fi
 fi
@@ -37,17 +49,17 @@ if [ ! -f ${ABS_PATH}/../config/quads.csv ]
 then
   if [ -f ${ABS_PATH}/../config.bak/quads.csv ]
   then
-    echo "WARNING: Restoring Previous Quads file, may differ from stock units file provided by Archie"
+    echo -e "${Yello}WARNING: Restoring Previous Quads file, may differ from stock units file provided by Archie${Off}"
     cp ${ABS_PATH}/../config.bak/quads.csv ${ABS_PATH}/../config/quads.csv
   else
-    echo "WARNING: Quads config not found, copying dist into place."
+    echo -e "${Yellow}WARNING: Quads config not found, copying dist into place.${Off}"
     cp ${ABS_PATH}/../config/quads.csv.dist ${ABS_PATH}/../config/quads.csv
   fi
 fi
 
 if id -u "www-data" > /dev/null 2>&1; then
-  echo "Resetting file ownership to web user"
+  echo -e "${Green}Resetting file ownership to web user${Off}"
   chown -R www-data.www-data ${ABS_PATH}/../ 2>/dev/null
 fi
-
+echo -e "${BGreen}Update Finished${Off}"
 exit 0
